"use client"

import Image from "next/image"
import Link from "next/link"
import Script from "next/script"
import { useState } from "react"

export default function TechnologiesClientPage({ params }: { params: { lang: string } }) {
  const [lightboxImage, setLightboxImage] = useState<string | null>(null)

  // Define technologies with their details
  const technologies = [
    {
      id: "thread-lifts",
      title: params.lang === "pt" ? "Fios Tensores" : "Thread Lifts",
      description:
        params.lang === "pt"
          ? "Os fios tensores são uma técnica minimamente invasiva para lifting facial, proporcionando um efeito de sustentação e rejuvenescimento imediato. Estes fios são inseridos sob a pele para elevar e sustentar os tecidos faciais, estimulando também a produção de colágeno ao longo do tempo."
          : "Thread lifts are a minimally invasive technique for facial lifting, providing an immediate lifting and rejuvenating effect. These threads are inserted under the skin to elevate and support facial tissues, also stimulating collagen production over time.",
      benefits:
        params.lang === "pt"
          ? [
              "Efeito lifting imediato",
              "Estimulação da produção de colágeno",
              "Procedimento minimamente invasivo",
              "Recuperação rápida",
              "Resultados duradouros (1-2 anos)",
            ]
          : [
              "Immediate lifting effect",
              "Stimulation of collagen production",
              "Minimally invasive procedure",
              "Quick recovery",
              "Long-lasting results (1-2 years)",
            ],
      ideal:
        params.lang === "pt"
          ? "Ideal para pessoas com flacidez facial leve a moderada, que desejam um rejuvenescimento sem cirurgia."
          : "Ideal for people with mild to moderate facial sagging who want rejuvenation without surgery.",
      image: "/facial-marking-procedure.jpeg",
    },
    {
      id: "dermapen",
      title: "Dermapen",
      description:
        params.lang === "pt"
          ? "O Dermapen é um dispositivo de microagulhamento avançado que cria microcanais na pele de forma controlada e precisa. Este procedimento estimula a regeneração natural da pele, promovendo a produção de colágeno e elastina, resultando em uma pele mais firme, lisa e rejuvenescida."
          : "Dermapen is an advanced microneedling device that creates microchannels in the skin in a controlled and precise manner. This procedure stimulates the skin's natural regeneration, promoting collagen and elastin production, resulting in firmer, smoother, and rejuvenated skin.",
      benefits:
        params.lang === "pt"
          ? [
              "Melhora a textura e firmeza da pele",
              "Reduz cicatrizes de acne e estrias",
              "Minimiza poros dilatados",
              "Uniformiza o tom da pele",
              "Aumenta a absorção de produtos tópicos",
            ]
          : [
              "Improves skin texture and firmness",
              "Reduces acne scars and stretch marks",
              "Minimizes enlarged pores",
              "Evens skin tone",
              "Increases absorption of topical products",
            ],
      ideal:
        params.lang === "pt"
          ? "Ideal para tratar cicatrizes de acne, linhas finas, rugas, poros dilatados, estrias e melhorar a textura geral da pele."
          : "Ideal for treating acne scars, fine lines, wrinkles, enlarged pores, stretch marks, and improving overall skin texture.",
      image: "/dermapen-treatment.jpeg",
    },
    {
      id: "rf-microneedling",
      title: params.lang === "pt" ? "Microagulhamento com Radiofrequência" : "Radiofrequency Microneedling",
      description:
        params.lang === "pt"
          ? "Esta tecnologia combina o microagulhamento tradicional com a energia de radiofrequência, que é liberada diretamente nas camadas mais profundas da pele. O calor gerado pela radiofrequência potencializa a produção de colágeno e elastina, proporcionando resultados superiores ao microagulhamento convencional."
          : "This technology combines traditional microneedling with radiofrequency energy, which is delivered directly to the deeper layers of the skin. The heat generated by radiofrequency enhances collagen and elastin production, providing superior results compared to conventional microneedling.",
      benefits:
        params.lang === "pt"
          ? [
              "Efeito lifting mais pronunciado",
              "Redução significativa de rugas e linhas de expressão",
              "Melhora acentuada da flacidez cutânea",
              "Tratamento eficaz para cicatrizes profundas",
              "Resultados visíveis com menos sessões",
            ]
          : [
              "More pronounced lifting effect",
              "Significant reduction of wrinkles and expression lines",
              "Marked improvement in skin laxity",
              "Effective treatment for deep scars",
              "Visible results with fewer sessions",
            ],
      ideal:
        params.lang === "pt"
          ? "Ideal para pessoas que buscam um rejuvenescimento mais intenso, com melhora da flacidez facial e corporal, redução de rugas profundas e tratamento de cicatrizes."
          : "Ideal for people seeking more intense rejuvenation, with improvement in facial and body sagging, reduction of deep wrinkles, and treatment of scars.",
      image: "/microneedling-treatment.jpeg",
    },
    {
      id: "botulinum-toxin",
      title: params.lang === "pt" ? "Toxina Botulínica" : "Botulinum Toxin",
      description:
        params.lang === "pt"
          ? "A toxina botulínica é uma substância que, quando aplicada em pequenas doses, relaxa temporariamente os músculos, suavizando as rugas dinâmicas (aquelas causadas pela expressão facial). O tratamento é rápido, seguro e proporciona um aspecto natural quando realizado por profissionais experientes."
          : "Botulinum toxin is a substance that, when applied in small doses, temporarily relaxes the muscles, smoothing dynamic wrinkles (those caused by facial expression). The treatment is quick, safe, and provides a natural appearance when performed by experienced professionals.",
      benefits:
        params.lang === "pt"
          ? [
              "Suavização de rugas de expressão",
              "Prevenção do aprofundamento de rugas",
              "Procedimento rápido e sem tempo de recuperação",
              "Resultados visíveis em poucos dias",
              "Efeito que dura de 4 a 6 meses",
            ]
          : [
              "Smoothing of expression wrinkles",
              "Prevention of wrinkle deepening",
              "Quick procedure with no recovery time",
              "Visible results in a few days",
              "Effect lasting 4 to 6 months",
            ],
      ideal:
        params.lang === "pt"
          ? "Ideal para suavizar rugas da testa, entre as sobrancelhas (glabela) e ao redor dos olhos (pés de galinha), além de tratar o bruxismo, sorriso gengival e hiperidrose (suor excessivo)."
          : "Ideal for smoothing forehead wrinkles, between the eyebrows (glabellar lines), and around the eyes (crow's feet), as well as treating bruxism, gummy smile, and hyperhidrosis (excessive sweating).",
      image: "/doutor-desenho-com-marcador-no-rosto-de-alto-angulo.jpg",
    },
    {
      id: "hyaluronic-acid",
      title: params.lang === "pt" ? "Ácido Hialurónico" : "Hyaluronic Acid",
      description:
        params.lang === "pt"
          ? "O ácido hialurónico é uma substância naturalmente presente na pele, responsável pela hidratação, firmeza e elasticidade. Os preenchimentos à base de ácido hialurónico são utilizados para restaurar volume, preencher rugas profundas e remodelar contornos faciais, com resultados imediatos e naturais."
          : "Hyaluronic acid is a substance naturally present in the skin, responsible for hydration, firmness, and elasticity. Hyaluronic acid-based fillers are used to restore volume, fill deep wrinkles, and reshape facial contours, with immediate and natural results.",
      benefits:
        params.lang === "pt"
          ? [
              "Restauração de volume facial",
              "Preenchimento de rugas e sulcos profundos",
              "Hidratação profunda da pele",
              "Definição e contorno labial",
              "Resultados imediatos e naturais",
            ]
          : [
              "Restoration of facial volume",
              "Filling of deep wrinkles and folds",
              "Deep skin hydration",
              "Lip definition and contouring",
              "Immediate and natural results",
            ],
      ideal:
        params.lang === "pt"
          ? "Ideal para restaurar volume nas maçãs do rosto, preencher o sulco nasolabial e linhas de marionete, definir o contorno e volume dos lábios, e melhorar o contorno da mandíbula."
          : "Ideal for restoring volume in the cheeks, filling nasolabial folds and marionette lines, defining lip contour and volume, and improving jawline contour.",
      image: "/lip-filler-injection.jpeg",
      additionalImage: "/hyaluronic-acid-gel.jpeg",
    },
  ]

  // Function to open lightbox
  const openLightbox = (imageSrc: string) => {
    setLightboxImage(imageSrc)
    // Prevent scrolling when lightbox is open
    document.body.style.overflow = "hidden"
  }

  // Function to close lightbox
  const closeLightbox = () => {
    setLightboxImage(null)
    // Re-enable scrolling
    document.body.style.overflow = "auto"
  }

  return (
    <>
      <Script
        id="technologies-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "MedicalWebPage",
            about: {
              "@type": "MedicalBusiness",
              name: "Dr. Henrique Oliveira - Dermatologia",
              medicalSpecialty: ["Dermatology", "Aesthetic Dermatology"],
            },
            mainEntity: {
              "@type": "ItemList",
              itemListElement: technologies.map((tech, index) => ({
                "@type": "ListItem",
                position: index + 1,
                item: {
                  "@type": "MedicalProcedure",
                  name: tech.title,
                  description: tech.description,
                },
              })),
            },
          }),
        }}
      />
      <div className="bg-[#FAFAFA]">
        {/* Hero Section */}
        <section className="bg-[#FFFFFF] py-16">
          <div className="container mx-auto px-6">
            <div className="max-w-4xl mx-auto text-center">
              <h1 className="heading-xl mb-6">
                {params.lang === "pt" ? "Tecnologias Avançadas" : "Advanced Technologies"}
              </h1>
              <p className="text-lg text-gray-700">
                {params.lang === "pt"
                  ? "Conheça as tecnologias e tratamentos de ponta utilizados pelo Dr. Henrique Oliveira para proporcionar resultados excepcionais."
                  : "Learn about the cutting-edge technologies and treatments used by Dr. Henrique Oliveira to provide exceptional results."}
              </p>
            </div>
          </div>
        </section>

        {/* Technologies Section */}
        <section className="py-16">
          <div className="container mx-auto px-6">
            <div className="max-w-5xl mx-auto">
              {technologies.map((tech, index) => (
                <div
                  key={tech.id}
                  id={tech.id}
                  className={`mb-16 ${
                    index % 2 === 0 ? "lg:flex-row" : "lg:flex-row-reverse"
                  } flex flex-col lg:flex-row items-center gap-10`}
                >
                  <div className="lg:w-1/2">
                    {tech.additionalImage ? (
                      <div className="grid grid-cols-1 gap-4">
                        <div
                          className="relative h-80 w-full rounded-xl overflow-hidden shadow-md cursor-pointer"
                          onClick={() => openLightbox(tech.image)}
                        >
                          <Image
                            src={tech.image || "/placeholder.svg"}
                            alt={tech.title}
                            fill
                            className="object-cover"
                            unoptimized={true}
                          />
                        </div>
                        <div
                          className="relative h-40 w-full rounded-xl overflow-hidden shadow-md cursor-pointer"
                          onClick={() => openLightbox(tech.additionalImage)}
                        >
                          <Image
                            src={tech.additionalImage || "/placeholder.svg"}
                            alt={`${tech.title} - ${params.lang === "pt" ? "Detalhe" : "Detail"}`}
                            fill
                            className="object-cover"
                            unoptimized={true}
                          />
                        </div>
                      </div>
                    ) : (
                      <div
                        className="relative h-80 w-full rounded-xl overflow-hidden shadow-md cursor-pointer"
                        onClick={() => openLightbox(tech.image)}
                      >
                        <Image
                          src={tech.image || "/placeholder.svg"}
                          alt={tech.title}
                          fill
                          className="object-cover"
                          unoptimized={true}
                        />
                      </div>
                    )}
                  </div>
                  <div className="lg:w-1/2">
                    <h2 className="heading-md mb-4" style={{ color: "#2E2E2E" }}>
                      {tech.title}
                    </h2>
                    <p className="text-gray-700 mb-6">{tech.description}</p>
                    <div className="mb-6">
                      <h3 className="font-medium text-lg mb-3" style={{ color: "#f96c8b" }}>
                        {params.lang === "pt" ? "Benefícios" : "Benefits"}
                      </h3>
                      <ul className="space-y-2 text-gray-700">
                        {tech.benefits.map((benefit, i) => (
                          <li key={i} className="flex items-start">
                            <span
                              className="inline-block w-2 h-2 mt-2 mr-2 relative"
                              style={{
                                border: "1px solid #f5c8df",
                                borderRadius: "0% 50% 50% 50%",
                                transform: "rotate(45deg)",
                                backgroundColor: "transparent",
                              }}
                            ></span>
                            <span>{benefit}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div className="p-4 bg-[#f8ebef] rounded-lg">
                      <p className="text-gray-700">
                        <span className="font-medium">{params.lang === "pt" ? "Indicações: " : "Indications: "}</span>
                        {tech.ideal}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Consultation CTA */}
        <section className="py-16" style={{ backgroundColor: "#e8e8e8" }}>
          <div className="container mx-auto px-6">
            <div className="max-w-4xl mx-auto text-center">
              <h2 className="heading-md mb-6" style={{ color: "#2E2E2E" }}>
                {params.lang === "pt"
                  ? "Agende uma consulta para avaliação personalizada"
                  : "Schedule a consultation for personalized assessment"}
              </h2>
              <p className="text-lg text-[#2E2E2E] mb-8">
                {params.lang === "pt"
                  ? "Entre em contato para agendar uma avaliação e descobrir quais tecnologias são mais adequadas para suas necessidades específicas."
                  : "Contact us to schedule an assessment and discover which technologies are most suitable for your specific needs."}
              </p>
              <Link
                href={`/${params.lang}/${params.lang === "pt" ? "contato" : "contact"}`}
                className="inline-block px-8 py-3 rounded-xl text-sm tracking-wide transition"
                style={{ backgroundColor: "#f96c8b", color: "white" }}
              >
                {params.lang === "pt" ? "Agendar Consulta" : "Schedule Appointment"}
              </Link>
            </div>
          </div>
        </section>

        {/* FAQ Teaser */}
        <section className="py-16 bg-white">
          <div className="container mx-auto px-6">
            <div className="max-w-4xl mx-auto text-center">
              <h2 className="heading-lg mb-4" style={{ color: "#2E2E2E" }}>
                {params.lang === "pt" ? "Perguntas Frequentes" : "Frequently Asked Questions"}
              </h2>
              <p className="text-lg text-gray-700 mb-8">
                {params.lang === "pt"
                  ? "Encontre respostas para as dúvidas mais comuns sobre nossos tratamentos e tecnologias"
                  : "Find answers to the most common questions about our treatments and technologies"}
              </p>
              <Link
                href={`/${params.lang}/faq`}
                className="inline-block px-8 py-3 rounded-xl text-sm tracking-wide transition"
                style={{ backgroundColor: "#a09f9e", color: "white" }}
              >
                {params.lang === "pt" ? "Ver Todas as Perguntas" : "View All Questions"}
              </Link>
            </div>
          </div>
        </section>
      </div>

      {/* Lightbox */}
      {lightboxImage && (
        <div
          className="fixed inset-0 bg-black bg-opacity-90 z-50 flex items-center justify-center p-4"
          onClick={closeLightbox}
        >
          <div className="relative max-w-4xl max-h-[90vh] w-full h-full flex items-center justify-center">
            <button
              className="absolute top-4 right-4 text-white bg-black bg-opacity-50 rounded-full p-2 z-10"
              onClick={closeLightbox}
              aria-label="Close lightbox"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
            <div className="relative w-full h-full flex items-center justify-center">
              <img
                src={lightboxImage || "/placeholder.svg"}
                alt="Enlarged view"
                className="max-w-full max-h-full object-contain cursor-pointer"
                onClick={(e) => {
                  e.stopPropagation()
                  closeLightbox()
                }}
              />
            </div>
          </div>
        </div>
      )}
    </>
  )
}
